### ISSUE TITLE
Binary File Reduction

### ISSUE THREAD

**Issue by catherine-leung** [Seneca-ICTOER/OERTemplate#17]
There are a number of image files we have as part of instructions that probably shouldn't be part of the template.  binaries will bloat repos created from this template unncessarily. 

Suggested solution:

* Create a github repo with pages turned on and throw all images that are not part of docusaurus framework into the repo
* update all the links to refer to those images.
* remove all unnecessary images from repo

This will reduce the bloat for new OER's

@CameronGray1210 thoughts?

**Comment by CameronGray1210** [comment]
👍 Good idea! possible names:  OERTemplateResources, OERResources, OERTemplateBinaries, OERBinaries....

**Comment by catherine-leung** [comment]
I'll use OERResources.  I will put the images for this repo under OERTemplate.  If others wish to not bloat their repos, they can put the images into this repo also.
