### ISSUE TITLE
Change to template repo?

### ISSUE THREAD

**Issue by catherine-leung** [Seneca-ICTOER/OERTemplate#3]
I think we should change this to a template repo as a starting point so that others who wish to build their OERs can make use of it.  Instructions to this should also be updated to match.

**Comment by CameronGray1210** [comment]
That was the intention of this repo! Happy to see you're refining it - Thanks Cathy.

**Comment by catherine-leung** [comment]
I can get patch for that up pretty quickly.  But perhaps start with the PAT patch

**Comment by catherine-leung** [comment]
I just tried making this change.. and there are a few issues.  Please let me know your thoughts on this @CameronGray1210 

1) Currently README.md and CONTRIBUTE.md are exactly the same.  I think we should change the README.md file so that it has instructions on using this template instead of for contributions.

2) CNAME.  As the deployment script is triggered on the initial commit, this file is problematic as every repo really should be using its own name as opposed to the name here.  Recommend that we remove this file and add instructions on creating it in the README.md

Thoughts?

**Comment by catherine-leung** [comment]
So, if you create a repo off the template with intension of making it an OER about say. cookie making, cookie101, the template repo is fully duplicated.  Whether or you fork or use template, this still happens.  Thus the CName file is always what it is in the template repo.  The deployment will throw an error... here is what I got in an email... it seems to stop complaining after the first run though.  However, even if its not throwing an error, it is still wrong for the cookie making course.  Thus, we need to add instructions on what to change it to:
```
The page build completed successfully, but returned the following warning for the `gh-pages` branch:

The custom domain `[seneca-ictoer.github.io/oertemplate/](https://protect-us.mimecast.com/s/ikrCC0RyD4CyPLZ9cOrs_M?domain=seneca-ictoer.github.io)` is not properly formatted. See[ https://docs.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors](https://protect-us.mimecast.com/s/0LR5CgJVMvCBQ7pjU7CXPW?domain=docs.github.com) for more information.

For information on troubleshooting Jekyll see:

[https://docs.github.com/articles/troubleshooting-jekyll-builds](https://protect-us.mimecast.com/s/fJmWCjRV6yCONvPwFjREV1?domain=docs.github.com)

If you have any questions you can submit a request at[ https://support.github.com/contact?tags=dotcom-pages&repo_id=508988022&page_build_id=353812728](https://protect-us.mimecast.com/s/h4djCkRVXzCwGp1RFNJc8B?domain=support.github.com)

```

**Comment by catherine-leung** [comment]
@CameronGray1210 thoughts on above?

**Comment by CameronGray1210** [comment]
@catherine-leung To avoid errors the CNAME needs to contain the root URL of the published site.  The default is that of the GitHub as you have set it in the OERTemplate, but when it is officially published using another domain (such as how we are setting up our OER's for SDDS) then it must contain the official subdomain name with the main domain. 

I think the way you have set it by default is good for initial copying and developing. BUT, yes, this needs to be documented to indicate what needs to change when publishing.

Also of note, the docusaurus.config.js file also requires documenting which plays a role in the URL information as well.

**Comment by catherine-leung** [comment]
I will add that to the instructions.
